services:
  comfyui:
    image: ghcr.io/luxuride/comfyui-rocm-docker:latest
    container_name: comfyui-rocm
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ./models:/opt/ComfyUI/models
      - ./input:/opt/ComfyUI/input
      - ./output:/opt/ComfyUI/output
      - ./custom_nodes:/opt/ComfyUI/custom_nodes
      - ./user:/opt/ComfyUI/user
    ports:
      - "8188:8188"
    restart: unless-stopped

